### ISSUE TITLE
Plugin Fails in 1.10.2

### ISSUE THREAD

**Issue by hoorigan** [Kyzderp/AutoCraftMod#3]
This probably goes beyond intended use, but I modified the litemod.json file to see if I could get the mod to run in MC 1.10.2, and it crashes.  Are there any plans to update this mod?

**Comment by hoorigan** [comment]
Logged error output follows:

`[18:40:22] [Client thread/INFO]: Loading mod from io.github.kyzderp.autocraftmod.LiteModAutoCraft
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]: java.lang.NoClassDefFoundError: cio
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at java.lang.Class.getDeclaredConstructors0(Native Method)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at java.lang.Class.getConstructor0(Class.java:3075)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at java.lang.Class.newInstance(Class.java:412)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at com.mumfrey.liteloader.core.Mod.newInstance(Mod.java:88)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at com.mumfrey.liteloader.core.LiteLoaderMods.loadMod(LiteLoaderMods.java:499)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at com.mumfrey.liteloader.core.LiteLoaderMods.loadMods(LiteLoaderMods.java:454)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at com.mumfrey.liteloader.core.LiteLoader.loadAndInitMods(LiteLoader.java:861)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at com.mumfrey.liteloader.core.LiteLoader.onPostInit(LiteLoader.java:291)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at com.mumfrey.liteloader.core.LiteLoader.invokePostInit(LiteLoader.java:1050)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at com.mumfrey.liteloader.core.LiteLoaderBootstrap.postInit(LiteLoaderBootstrap.java:393)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at com.mumfrey.liteloader.launch.LiteLoaderTweaker.onPostInit(LiteLoaderTweaker.java:412)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at com.mumfrey.liteloader.launch.LiteLoaderTweaker.postInit(LiteLoaderTweaker.java:684)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at net.minecraft.client.main.Main.main(SourceFile:124)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at java.lang.reflect.Method.invoke(Method.java:498)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[18:40:22] [Client thread/INFO]: [com.mumfrey.liteloader.core.LiteLoaderMods:loadMods:468]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:40:22] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.ClassNotFoundException: cio
[18:40:22] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[18:40:22] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[18:40:22] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]:     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[18:40:22] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:634]:     ... 22 more
[18:40:22] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[18:40:22] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:643]:     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[18:40:22] [Client thread/INFO]: [java.lang.Throwable:printStackTrace:643]:     ... 24 more
[18:40:22] [Client thread/WARN]: Not loading mod io.github.kyzderp.autocraftmod.LiteModAutoCraft, an error occurred
[18:40:22] [Client thread/ERROR]: Error during LiteLoader POSTINIT: java.lang.NullPointerException null
java.lang.NullPointerException
        at com.mumfrey.liteloader.client.ResourceObserver.onPostModLoaded(ResourceObserver.java:50) ~[liteloader-1.10.2-SNAPSHOT.jar:1.10.2-SNAPSHOT+jnks-b6.git-ff13a62c8cd27e67b6f886f216016cd65c5f59b8]
        at com.mumfrey.liteloader.core.event.HandlerList$ModLoadObserver2.onPostModLoaded(HandlerList$ModLoadObserver2.java:100) ~[?:?]
        at com.mumfrey.liteloader.core.LiteLoaderMods.loadMods(LiteLoaderMods.java:473) ~[liteloader-1.10.2-SNAPSHOT.jar:1.10.2-SNAPSHOT+jnks-b6.git-ff13a62c8cd27e67b6f886f216016cd65c5f59b8]
        at com.mumfrey.liteloader.core.LiteLoader.loadAndInitMods(LiteLoader.java:861) ~[liteloader-1.10.2-SNAPSHOT.jar:1.10.2-SNAPSHOT+jnks-b6.git-ff13a62c8cd27e67b6f886f216016cd65c5f59b8]
        at com.mumfrey.liteloader.core.LiteLoader.onPostInit(LiteLoader.java:291) ~[liteloader-1.10.2-SNAPSHOT.jar:1.10.2-SNAPSHOT+jnks-b6.git-ff13a62c8cd27e67b6f886f216016cd65c5f59b8]
        at com.mumfrey.liteloader.core.LiteLoader.invokePostInit(LiteLoader.java:1050) ~[liteloader-1.10.2-SNAPSHOT.jar:1.10.2-SNAPSHOT+jnks-b6.git-ff13a62c8cd27e67b6f886f216016cd65c5f59b8]
        at com.mumfrey.liteloader.core.LiteLoaderBootstrap.postInit(LiteLoaderBootstrap.java:393) ~[liteloader-1.10.2-SNAPSHOT.jar:1.10.2-SNAPSHOT+jnks-b6.git-ff13a62c8cd27e67b6f886f216016cd65c5f59b8]
        at com.mumfrey.liteloader.launch.LiteLoaderTweaker.onPostInit(LiteLoaderTweaker.java:412) [liteloader-1.10.2-SNAPSHOT.jar:1.10.2-SNAPSHOT+jnks-b6.git-ff13a62c8cd27e67b6f886f216016cd65c5f59b8]
        at com.mumfrey.liteloader.launch.LiteLoaderTweaker.postInit(LiteLoaderTweaker.java:684) [liteloader-1.10.2-SNAPSHOT.jar:1.10.2-SNAPSHOT+jnks-b6.git-ff13a62c8cd27e67b6f886f216016cd65c5f59b8]
        at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509) [bcx.class:?]
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]`
